### ISSUE TITLE
errors in red in log

### ISSUE THREAD

**Issue by firelook** [CrimsonMods/CrimsonQuest#3]
I have that
`[Info   :CrimsonQuest] Searching for Flairsou's progress.
[Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at CrimsonQuest.Utils.QuestService.UpdateMobQuestProgress(UserModel player, QuestProgressModel progress, PrefabGUID mob)
   at CrimsonQuest.Hooks.QuestHooks.OnUpdate_KillMobs(OnKillSystem __instance)
   at DMD<ProjectM.Gameplay.Systems.OnKillSystem::OnUpdate>(OnKillSystem this)
   at (il2cpp -> managed) OnUpdate(IntPtr , Il2CppMethodInfo* )
[Info   :CrimsonQuest] Searching for Flairsou's progress.
[Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at CrimsonQuest.Utils.QuestService.UpdateMobQuestProgress(UserModel player, QuestProgressModel progress, PrefabGUID mob)
   at CrimsonQuest.Hooks.QuestHooks.OnUpdate_KillMobs(OnKillSystem __instance)
   at DMD<ProjectM.Gameplay.Systems.OnKillSystem::OnUpdate>(OnKillSystem this)
   at (il2cpp -> managed) OnUpdate(IntPtr , Il2CppMethodInfo* )
[Message:     Unity] Triggering AutoSave 19815!`

my files
[quest_tracker.json](https://github.com/user-attachments/files/16323345/quest_tracker.json)
[quest_list.json](https://github.com/user-attachments/files/16323347/quest_list.json)
[quest_givers.json](https://github.com/user-attachments/files/16323348/quest_givers.json)

**Comment by firelook** [comment]
no more red lines
